spring.application.name=api
spring.datasource.url=jdbc:h2:mem:issuetracker;database_to_lower=true;
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.jpa.defer-datasource-initialization=true
server.port=8000

# Mínimo 32 caracteres, que son 256 bits UTF8
jwt.secret=Hola_esto_tiene_que_tener_al_menos_32_caracteres_para_que_funcione.
jwt.access-token.expiration=30000000
