spring.application.name=api
server.port=8000

# Perfil activo por defecto
spring.profiles.active=dev

# Configuracin JWT (Comn a todos los perfiles)
jwt.secret=Hola_esto_tiene_que_tener_al_menos_32_caracteres_para_que_funcione.
jwt.access-token.expiration=30000000
